"""Expected PostgreSQL catalog identities and semantic constraints."""

from pathlib import Path
from typing import TypeAlias

ForeignKey: TypeAlias = tuple[tuple[str, ...], str, tuple[str, ...]]

SCHEMA = Path("db/schema.sql").resolve()
TABLES = {
    "tb_universe",
    "tb_daily_pick",
    "tb_technical",
    "tb_macro",
    "tb_disclosure",
    "tb_disclosure_signal",
    "tb_news",
    "tb_news_signal",
    "tb_strategist_signals",
    "tb_critic_verdict",
    "tb_account",
    "tb_order",
    "tb_fill",
    "tb_review_price_snapshots",
    "tb_review",
    "pipeline_runs",
    "pipeline_stage_attempts",
    "pipeline_checkpoints",
    "order_submissions",
}
PK = {
    "tb_universe": ("as_of_date", "ticker"),
    "tb_daily_pick": ("trade_date", "ticker"),
    "tb_technical": ("trade_date", "ticker"),
    "tb_macro": ("as_of",),
    "tb_disclosure": ("id",),
    "tb_disclosure_signal": ("tds_id",),
    "tb_news": ("id",),
    "tb_news_signal": ("tns_id",),
    "tb_strategist_signals": ("id",),
    "tb_critic_verdict": ("id",),
    "tb_account": ("id",),
    "tb_order": ("id",),
    "tb_fill": ("id",),
    "tb_review_price_snapshots": ("signal_id", "day_offset"),
    "tb_review": ("signal_id",),
    "pipeline_runs": ("run_id",),
    "pipeline_stage_attempts": ("attempt_id",),
    "pipeline_checkpoints": ("checkpoint_id",),
    "order_submissions": ("submission_id",),
}
UNIQUE = {
    "tb_disclosure": {("filing_no",)},
    "tb_disclosure_signal": {("ticker", "cycle_ts")},
    "tb_news": {("news_key", "ticker")},
    "tb_news_signal": {("ticker", "cycle_ts")},
    "tb_strategist_signals": {("ticker", "cycle_ts", "inv_type")},
    "tb_critic_verdict": {("signal_id",)},
    "tb_account": {("broker_account_id",)},
    "tb_order": {
        ("broker_order_id",),
        ("idempotency_key",),
        ("account_id", "signal_id"),
    },
    "tb_fill": {("broker_fill_id",)},
    "pipeline_runs": {("idempotency_key",)},
    "pipeline_stage_attempts": {("run_id", "component", "attempt_no")},
    "pipeline_checkpoints": {("run_id", "component")},
    "order_submissions": {("client_order_id",)},
}

ORDER_LEG_COLUMNS = {
    "parent_order_id",
    "stop_leg_order_id",
    "take_profit_leg_order_id",
}

PROVENANCE_COLUMNS = {
    "tb_disclosure": {
        ("source", "NO"),
        ("source_ref", "NO"),
        ("captured_at", "NO"),
        ("evidence_id", "NO"),
        ("parent_evidence_ids", "NO"),
        ("model_provider", "NO"),
        ("model_name", "YES"),
        ("prompt_version", "YES"),
        ("policy_version", "YES"),
        ("input_hash", "YES"),
    },
    "tb_disclosure_signal": {
        ("source", "NO"),
        ("source_ref", "NO"),
        ("captured_at", "NO"),
        ("evidence_id", "NO"),
        ("parent_evidence_ids", "NO"),
        ("model_provider", "NO"),
        ("model_name", "YES"),
        ("prompt_version", "YES"),
        ("policy_version", "YES"),
        ("input_hash", "YES"),
    },
    "tb_news": {
        ("source", "NO"),
        ("source_ref", "NO"),
        ("captured_at", "NO"),
        ("evidence_id", "NO"),
        ("parent_evidence_ids", "NO"),
        ("model_provider", "NO"),
        ("model_name", "YES"),
        ("prompt_version", "YES"),
        ("policy_version", "YES"),
        ("input_hash", "YES"),
    },
    "tb_news_signal": {
        ("source_ref", "NO"),
        ("captured_at", "NO"),
        ("evidence_id", "NO"),
        ("parent_evidence_ids", "NO"),
        ("model_provider", "NO"),
        ("model_name", "YES"),
        ("prompt_version", "YES"),
        ("policy_version", "YES"),
        ("input_hash", "YES"),
    },
    "tb_review_price_snapshots": {
        ("source_ref", "NO"),
        ("observed_at", "NO"),
        ("captured_at", "NO"),
        ("confidence", "NO"),
        ("evidence_id", "NO"),
        ("parent_evidence_ids", "NO"),
        ("model_provider", "YES"),
        ("model_name", "YES"),
        ("prompt_version", "YES"),
        ("policy_version", "YES"),
        ("input_hash", "YES"),
    },
}
FK: dict[str, set[ForeignKey]] = {
    "tb_daily_pick": {(("universe_as_of", "ticker"), "tb_universe", ("as_of_date", "ticker"))},
    "tb_technical": {(("trade_date", "ticker"), "tb_daily_pick", ("trade_date", "ticker"))},
    "tb_disclosure": {(("trade_date", "ticker"), "tb_daily_pick", ("trade_date", "ticker"))},
    "tb_disclosure_signal": {
        (("trade_date", "ticker"), "tb_daily_pick", ("trade_date", "ticker")),
        (("filing_no",), "tb_disclosure", ("filing_no",)),
    },
    "tb_news": {(("trade_date", "ticker"), "tb_daily_pick", ("trade_date", "ticker"))},
    "tb_news_signal": {
        (("trade_date", "ticker"), "tb_daily_pick", ("trade_date", "ticker")),
        (("rep_news_id",), "tb_news", ("id",)),
        (("disclosure_ref",), "tb_disclosure", ("filing_no",)),
    },
    "tb_strategist_signals": {
        (("trade_date", "ticker"), "tb_daily_pick", ("trade_date", "ticker")),
        (("ticker", "src_disclosure_at"), "tb_disclosure_signal", ("ticker", "cycle_ts")),
        (("ticker", "src_news_at"), "tb_news_signal", ("ticker", "cycle_ts")),
        (("src_macro_at",), "tb_macro", ("as_of",)),
    },
    "tb_critic_verdict": {(("signal_id",), "tb_strategist_signals", ("id",))},
    "tb_order": {
        (("signal_id",), "tb_strategist_signals", ("id",)),
        (("account_id",), "tb_account", ("id",)),
    },
    "tb_fill": {(("order_id",), "tb_order", ("id",))},
    "tb_review_price_snapshots": {(("signal_id",), "tb_strategist_signals", ("id",))},
    "tb_review": {(("signal_id",), "tb_strategist_signals", ("id",))},
    "pipeline_stage_attempts": {(("run_id",), "pipeline_runs", ("run_id",))},
    "pipeline_checkpoints": {(("run_id",), "pipeline_runs", ("run_id",))},
    "order_submissions": {
        (("run_id",), "pipeline_runs", ("run_id",)),
        (("order_id",), "tb_order", ("id",)),
    },
}
# Each tuple is one CHECK constraint and lists every semantic fragment it must contain.
CHECKS = {
    "tb_universe": {("market_cap",): ("market_cap >= 0",)},
    "tb_daily_pick": {
        ("bucket",): ("trend_leader", "backfill"),
        ("rank",): ("rank >= 1", "rank <= 50"),
    },
    "tb_technical": {("close",): ("close >",), ("trend",): ("'up'", "'no_data'")},
    "tb_macro": {
        ("regime",): ("'risk_on'", "'risk_off'"),
        ("risk_score",): ("risk_score >=", "risk_score <="),
    },
    "tb_disclosure": {
        ("sentiment_score",): ("sentiment_score >=", "sentiment_score <="),
        ("importance",): ("importance >=", "importance <="),
        ("risk_score",): ("risk_score >=", "risk_score <="),
        ("confidence",): ("confidence >=", "confidence <="),
        ("permission",): ("'block'", "'block_buy'", "'trade_eligible'"),
    },
    "tb_disclosure_signal": {
        ("importance",): ("importance >=", "importance <="),
        ("risk_score",): ("risk_score >=", "risk_score <="),
        ("sentiment_score",): ("sentiment_score >=", "sentiment_score <="),
        ("confidence",): ("confidence >=", "confidence <="),
    },
    "tb_news": {
        ("grade",): ("'allow'", "'gray'", "'block'"),
        ("sentiment_score",): ("sentiment_score >=", "sentiment_score <="),
        ("importance",): ("importance >=", "importance <="),
        ("risk_score",): ("risk_score >=", "risk_score <="),
        ("source_trust",): ("source_trust >=", "source_trust <="),
        ("confidence",): ("confidence >=", "confidence <="),
        ("permission",): ("'block'", "'block_buy'", "'trade_eligible'"),
    },
    "tb_news_signal": {
        ("news_count",): ("news_count >= 0",),
        ("importance",): ("importance >=", "importance <="),
        ("peak_importance",): ("peak_importance >=", "peak_importance <="),
        ("risk_score",): ("risk_score >=", "risk_score <="),
        ("sentiment_score",): ("sentiment_score >=", "sentiment_score <="),
        ("source_trust",): ("source_trust >=", "source_trust <="),
        ("grade_score",): ("grade_score >=", "grade_score <="),
        ("confidence",): ("confidence >=", "confidence <="),
    },
    "tb_strategist_signals": {
        ("inv_type",): ("'aggressive'", "'conservative'"),
        ("side",): ("'buy'", "'hold'"),
        ("conviction",): ("conviction >=", "conviction <="),
        ("signal_consensus",): ("signal_consensus >= 0", "signal_consensus <= 3"),
        ("decision_close",): ("decision_close >",),
        ("current_price",): ("current_price >",),
    },
    "tb_critic_verdict": {
        ("decision",): ("'pass'", "'reject'", "'hold'"),
        ("confidence",): ("confidence >=", "confidence <="),
        ("decided_layer",): ("'quality_gate'", "'hard_rule'", "'llm'", "'gate'"),
        ("source",): ("'fresh'", "'cache'", "'cooldown'"),
    },
    "tb_account": {
        ("cash",): ("cash >=",),
        ("equity",): ("equity >=",),
        ("buying_power",): ("buying_power >=",),
    },
    "tb_order": {
        ("quantity",): ("quantity > 0",),
        ("entry_price",): ("entry_price >",),
        ("stop_price",): ("stop_price >",),
        ("take_profit_price",): ("take_profit_price >",),
        ("order_type",): ("order_type = 'bracket'",),
        ("status",): ("'planned'", "'submitted'", "'filled'", "'failed'", "'canceled'"),
        ("stop_price", "entry_price", "take_profit_price"): (
            "stop_price < entry_price",
            "entry_price < take_profit_price",
        ),
    },
    "tb_fill": {
        ("side",): ("'buy'", "'sell'"),
        ("quantity",): ("quantity > 0",),
        ("price",): ("price >",),
    },
    "tb_review_price_snapshots": {
        ("day_offset",): ("day_offset >= 1", "day_offset <= 5"),
        ("close",): ("close >",),
        ("source",): ("'fixture'", "'market_data'"),
        ("confidence",): ("confidence >=", "confidence <="),
    },
    "tb_review": {("max_drawdown",): ("max_drawdown <=",)},
    "pipeline_runs": {
        ("status",): ("'pending'", "'running'", "'completed'", "'failed'", "'timed_out'")
    },
    "pipeline_stage_attempts": {
        ("attempt_no",): ("attempt_no > 0",),
        ("status",): (
            "'pending'",
            "'running'",
            "'retrying'",
            "'completed'",
            "'failed'",
            "'timed_out'",
        ),
    },
    "order_submissions": {
        ("state",): ("'claimed'", "'submitted'", "'completed'", "'failed'"),
        ("stale_after", "claimed_at"): ("stale_after > claimed_at",),
    },
}
